##### NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [4]:
mat = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [5]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

###### Aragnge
np.arange?? for more info

In [7]:
v = np.arange(12)

In [8]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

######  Reshape
np.reshape?? - for more info

In [14]:
x = v.reshape((4,3))
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
mat = np.arange(12).reshape((4,3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
mat2 = mat.reshape((3,4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#####  Slicing

In [17]:
nums = [1,2,3,4,5,6,7]
nums [2:4]

[3, 4]

In [18]:
v = np.array([3, 4])
v

array([3, 4])

###### Picking up specific elements from the matrix

In [22]:
arr = np.arange(12).reshape((3,4))

In [23]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr[:, 1]

array([1, 5, 9])

In [26]:
arr[1:, 2:] = 7 # broadcasting

In [27]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])